import type { Types } from 'mongoose';

import { planHasFeature } from '../contracts/index.js';
import { OrganizationModel } from '../models/index.js';
import {
  DEFAULT_BRANDING,
  safeHexColor,
  safeLogoUrl,
  type Branding,
} from '../reporting/branding.js';
import type { OrganizationContext } from '../types/common.types.js';

/**
 * Resolves an organization's branding.
 *
 * One place, because branding surfaces in three: PDF reports, the client portal
 * and public status pages. Two of those are seen by an agency's clients, and
 * they must not disagree about the agency's own name.
 *
 * **The plan gate is applied here rather than at each surface.** An organization
 * that had white labelling and downgraded keeps its stored branding — nothing
 * is deleted — but stops having it applied, and "Generated by SiteOps" comes
 * back. Enforcing that once means a downgrade cannot leave one surface still
 * white-labelled because somebody forgot a check.
 */
export class BrandingService {
  /**
   * Branding for a request that has already resolved its organization.
   *
   * Takes the context rather than an id so the plan is the one the middleware
   * loaded from the database, never a value from the request.
   */
  async forOrganization(organization: OrganizationContext): Promise<Branding> {
    if (!planHasFeature(organization.plan, 'white_label')) return DEFAULT_BRANDING;
    return this.load(organization.objectId);
  }

  /**
   * Branding for a context with no request behind it — the worker rendering a
   * scheduled report, or a public status page.
   *
   * Reads the plan from the organization document for the same reason: it is
   * the only authority on what a plan is.
   */
  async forOrganizationId(organizationId: Types.ObjectId): Promise<Branding> {
    return this.load(organizationId);
  }

  private async load(organizationId: Types.ObjectId): Promise<Branding> {
    const organization = await OrganizationModel.findById(organizationId)
      .select({ name: 1, plan: 1, branding: 1 })
      .lean<{
        name: string;
        plan: string;
        branding?: {
          brandName?: string | null;
          logoUrl?: string | null;
          primaryColor?: string | null;
          footerText?: string | null;
          hidePoweredBy?: boolean | null;
        } | null;
      }>()
      .exec();

    if (!organization) return DEFAULT_BRANDING;

    const entitled = planHasFeature(
      organization.plan as Parameters<typeof planHasFeature>[0],
      'white_label',
    );
    if (!entitled) return DEFAULT_BRANDING;

    const stored = organization.branding ?? null;

    return {
      brandName: stored?.brandName?.trim() ?? organization.name,
      // Both of these are re-validated on the way out, not merely on the way
      // in: they end up in a PDF and in an HTML attribute, and a document
      // written by anything other than the API must not be able to smuggle a
      // `javascript:` URL or a CSS-breaking colour into either.
      logoUrl: safeLogoUrl(stored?.logoUrl),
      primaryColor: safeHexColor(stored?.primaryColor, DEFAULT_BRANDING.primaryColor),
      footerText: stored?.footerText?.trim() ?? null,
      showPoweredBy: stored?.hidePoweredBy !== true,
    };
  }
}
