/**
 * The branding a rendered artefact carries.
 *
 * Shared by the PDF renderer and, later, the client portal and status pages, so
 * an agency's colours and name are applied identically wherever their client
 * sees them. Defined here rather than in the white-label feature because the
 * report renderer needed it first, and a second definition would drift.
 *
 * Every field has a SiteOps default, so an organization with no branding still
 * renders correctly rather than producing a document with holes in it.
 */
export interface Branding {
  /** Shown on the report and in the portal. Defaults to SiteOps. */
  readonly brandName: string;
  /** Absolute URL of a logo, or null. */
  readonly logoUrl: string | null;
  /** Hex colour used for headings and accents. */
  readonly primaryColor: string;
  /** Free text shown at the foot of a report, e.g. an agency's contact line. */
  readonly footerText: string | null;
  /** When false, "Generated by SiteOps" is shown. White-label plans may hide it. */
  readonly showPoweredBy: boolean;
}

export const DEFAULT_BRANDING: Branding = {
  brandName: 'SiteOps',
  logoUrl: null,
  primaryColor: '#4f46e5',
  footerText: null,
  showPoweredBy: true,
};

/**
 * A hex colour, or the default.
 *
 * Validated at the point of use rather than trusted from storage. The value
 * reaches a PDF renderer and, elsewhere, an HTML `style` attribute; anything
 * that is not literally six hex digits must never get that far, because
 * `#fff;}</style><script>` is a stored XSS the moment one of those surfaces
 * renders it. Storage validates it too — this is the second layer, and the one
 * that holds if a document is ever written by something other than the API.
 */
export function safeHexColor(value: string | null | undefined, fallback: string): string {
  if (typeof value !== 'string') return fallback;
  return /^#[0-9a-fA-F]{6}$/.test(value) ? value : fallback;
}

/**
 * An absolute `https` URL, or null.
 *
 * A logo URL is rendered into an `<img src>` and fetched by the PDF renderer, so
 * `javascript:` and `data:` are refused outright and plain HTTP is refused
 * because it would make an otherwise secure page mixed-content.
 */
export function safeLogoUrl(value: string | null | undefined): string | null {
  if (typeof value !== 'string' || value.length === 0) return null;

  try {
    const url = new URL(value);
    return url.protocol === 'https:' ? url.toString() : null;
  } catch {
    return null;
  }
}
