import { DEFAULT_PLAN, PLANS } from '../contracts/index.js';
import type { Plan } from '../contracts/index.js';
import mongoose, { Schema, model, type HydratedDocument, type Model, type Types } from 'mongoose';

/**
 * White-label branding.
 *
 * Stored regardless of plan and *applied* only on a plan that includes white
 * labelling — see `BrandingService`. An organization that downgrades keeps its
 * settings and gets them back on upgrading, rather than losing work it did.
 *
 * `primaryColor` and `logoUrl` are validated on write and again on read. They
 * reach a PDF renderer, an HTML `style` attribute and an `<img src>`, and a
 * value that skipped validation once must not become a stored XSS.
 */
export interface OrganizationBranding {
  brandName: string | null;
  logoUrl: string | null;
  primaryColor: string | null;
  footerText: string | null;
  /** Removes "Generated by SiteOps" from reports and portals. */
  hidePoweredBy: boolean;
  /** Address client-facing emails come from, once the domain is verified. */
  supportEmail: string | null;
}

export interface OrganizationAttributes {
  name: string;
  slug: string;
  plan: Plan;
  /** IANA zone used to render timestamps for everyone in the organization. */
  timezone: string;
  branding: OrganizationBranding;
  createdByUserId: Types.ObjectId;
  createdAt: Date;
  updatedAt: Date;
}

export type OrganizationDocument = HydratedDocument<OrganizationAttributes>;

const organizationSchema = new Schema<OrganizationAttributes>(
  {
    name: { type: String, required: true, trim: true, maxlength: 120 },
    slug: {
      type: String,
      required: true,
      trim: true,
      lowercase: true,
      maxlength: 48,
      // Uniqueness is enforced by the index declared below rather than by
      // `unique: true`, so index intent stays in one place.
    },
    plan: { type: String, required: true, enum: PLANS, default: DEFAULT_PLAN },
    timezone: { type: String, required: true, default: 'UTC', maxlength: 64 },
    branding: {
      type: new Schema<OrganizationBranding>(
        {
          brandName: { type: String, default: null, maxlength: 60 },
          logoUrl: { type: String, default: null, maxlength: 2048 },
          // Six hex digits, enforced at the storage layer as well as in the
          // validator: this value is interpolated into a style attribute.
          primaryColor: {
            type: String,
            default: null,
            match: /^#[0-9a-fA-F]{6}$/,
          },
          footerText: { type: String, default: null, maxlength: 200 },
          hidePoweredBy: { type: Boolean, required: true, default: false },
          supportEmail: { type: String, default: null, maxlength: 254 },
        },
        { _id: false },
      ),
      required: true,
      default: () => ({
        brandName: null,
        logoUrl: null,
        primaryColor: null,
        footerText: null,
        hidePoweredBy: false,
        supportEmail: null,
      }),
    },
    createdByUserId: { type: Schema.Types.ObjectId, required: true, ref: 'User' },
  },
  { timestamps: true, collection: 'organizations' },
);

// Slugs appear in URLs and must be globally unique.
organizationSchema.index({ slug: 1 }, { unique: true, name: 'organization_slug_unique' });

export const OrganizationModel: Model<OrganizationAttributes> =
  (mongoose.models.Organization as Model<OrganizationAttributes> | undefined) ??
  model<OrganizationAttributes>('Organization', organizationSchema);
