import {
  DEFAULT_PLAN,
  PLANS,
  SUBSCRIPTION_STATUSES,
  BILLING_INTERVALS,
} from '../contracts/index.js';
import type { BillingInterval, Plan, SubscriptionStatus } from '../contracts/index.js';
import mongoose, { Schema, model, type HydratedDocument, type Model, type Types } from 'mongoose';

/**
 * White-label branding.
 *
 * Stored regardless of plan and *applied* only on a plan that includes white
 * labelling — see `BrandingService`. An organization that downgrades keeps its
 * settings and gets them back on upgrading, rather than losing work it did.
 *
 * `primaryColor` and `logoUrl` are validated on write and again on read. They
 * reach a PDF renderer, an HTML `style` attribute and an `<img src>`, and a
 * value that skipped validation once must not become a stored XSS.
 */
export interface OrganizationBranding {
  brandName: string | null;
  logoUrl: string | null;
  primaryColor: string | null;
  footerText: string | null;
  /** Removes "Generated by SiteOps" from reports and portals. */
  hidePoweredBy: boolean;
  /** Address client-facing emails come from, once the domain is verified. */
  supportEmail: string | null;
}

/**
 * The organization's subscription, mirrored from the payment provider.
 *
 * Every field here is provider-owned truth. Nothing in SiteOps writes it in
 * response to a user action — the only writer is the webhook handler, reacting
 * to an event the provider signed. A user clicking "Upgrade" opens a checkout
 * session; the plan changes when the provider says it did, not when the browser
 * comes back.
 *
 * It is embedded rather than a collection of its own because an organization
 * has exactly one subscription and is never read without it: a separate
 * document would be a join on every entitlement check, for a one-to-one
 * relationship that cannot become one-to-many. Invoices and payment history
 * stay at the provider, which already renders them better than SiteOps would.
 *
 * `plan` deliberately does *not* live here. It stays on the organization, where
 * `EntitlementService` has always read it — so an organization with no billing
 * record at all is still a perfectly valid free-plan tenant, and a provider
 * outage cannot make every plan lookup fail.
 */
export interface OrganizationBilling {
  /** Provider customer id. Null until the first checkout completes. */
  customerId: string | null;
  subscriptionId: string | null;
  status: SubscriptionStatus;
  interval: BillingInterval | null;
  currentPeriodEnd: Date | null;
  cancelAtPeriodEnd: boolean;
  trialEndsAt: Date | null;
  /**
   * Provider clock for the last event applied.
   *
   * Webhooks are not ordered. Stripe will happily deliver a `deleted` and an
   * `updated` for the same subscription out of sequence, and applying the older
   * one second would leave the organization on the wrong plan indefinitely.
   * An event whose timestamp is older than this one is acknowledged and
   * discarded — see `BillingService.applySubscriptionState`.
   */
  lastEventAt: Date | null;
}

export interface OrganizationAttributes {
  name: string;
  slug: string;
  plan: Plan;
  /** IANA zone used to render timestamps for everyone in the organization. */
  timezone: string;
  branding: OrganizationBranding;
  billing: OrganizationBilling;
  createdByUserId: Types.ObjectId;
  createdAt: Date;
  updatedAt: Date;
}

export type OrganizationDocument = HydratedDocument<OrganizationAttributes>;

const organizationSchema = new Schema<OrganizationAttributes>(
  {
    name: { type: String, required: true, trim: true, maxlength: 120 },
    slug: {
      type: String,
      required: true,
      trim: true,
      lowercase: true,
      maxlength: 48,
      // Uniqueness is enforced by the index declared below rather than by
      // `unique: true`, so index intent stays in one place.
    },
    plan: { type: String, required: true, enum: PLANS, default: DEFAULT_PLAN },
    timezone: { type: String, required: true, default: 'UTC', maxlength: 64 },
    branding: {
      type: new Schema<OrganizationBranding>(
        {
          brandName: { type: String, default: null, maxlength: 60 },
          logoUrl: { type: String, default: null, maxlength: 2048 },
          // Six hex digits, enforced at the storage layer as well as in the
          // validator: this value is interpolated into a style attribute.
          primaryColor: {
            type: String,
            default: null,
            match: /^#[0-9a-fA-F]{6}$/,
          },
          footerText: { type: String, default: null, maxlength: 200 },
          hidePoweredBy: { type: Boolean, required: true, default: false },
          supportEmail: { type: String, default: null, maxlength: 254 },
        },
        { _id: false },
      ),
      required: true,
      default: () => ({
        brandName: null,
        logoUrl: null,
        primaryColor: null,
        footerText: null,
        hidePoweredBy: false,
        supportEmail: null,
      }),
    },
    billing: {
      type: new Schema<OrganizationBilling>(
        {
          customerId: { type: String, default: null, maxlength: 255 },
          subscriptionId: { type: String, default: null, maxlength: 255 },
          status: { type: String, required: true, enum: SUBSCRIPTION_STATUSES, default: 'none' },
          interval: { type: String, default: null, enum: [...BILLING_INTERVALS, null] },
          currentPeriodEnd: { type: Date, default: null },
          cancelAtPeriodEnd: { type: Boolean, required: true, default: false },
          trialEndsAt: { type: Date, default: null },
          lastEventAt: { type: Date, default: null },
        },
        { _id: false },
      ),
      required: true,
      default: () => ({
        customerId: null,
        subscriptionId: null,
        status: 'none',
        interval: null,
        currentPeriodEnd: null,
        cancelAtPeriodEnd: false,
        trialEndsAt: null,
        lastEventAt: null,
      }),
    },
    createdByUserId: { type: Schema.Types.ObjectId, required: true, ref: 'User' },
  },
  { timestamps: true, collection: 'organizations' },
);

// Slugs appear in URLs and must be globally unique.
organizationSchema.index({ slug: 1 }, { unique: true, name: 'organization_slug_unique' });

/*
 * Every webhook arrives naming a provider customer and nothing else, so this is
 * the lookup on the hot path of billing. Unique, because two organizations
 * sharing one provider customer would mean a single payment silently entitling
 * both.
 *
 * `partialFilterExpression` rather than `sparse`, and the difference is not
 * cosmetic: sparse excludes documents where the field is *absent*, but the
 * schema default above writes an explicit `null`. Every organization would
 * therefore carry an indexed `null`, and a unique index would allow exactly one
 * of them to exist. Filtering on `$type: 'string'` indexes only organizations
 * that actually have a customer, which is both the correct constraint and the
 * smaller index.
 */
organizationSchema.index(
  { 'billing.customerId': 1 },
  {
    unique: true,
    partialFilterExpression: { 'billing.customerId': { $type: 'string' } },
    name: 'organization_billing_customer_unique',
  },
);

export const OrganizationModel: Model<OrganizationAttributes> =
  (mongoose.models.Organization as Model<OrganizationAttributes> | undefined) ??
  model<OrganizationAttributes>('Organization', organizationSchema);
